name: Build, Analyze and Notify

on:
  push:
    branches:
      - main
      - dev

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outcome }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 모든 시크릿을 환경변수로 변환하는 단계
      - name: Export secrets as environment variables
        run: |
          # GitHub 시크릿을 JSON으로 변환하고 파싱하여 GitHub 환경 파일에 추가
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries | .[] | select(.key != "GITHUB_TOKEN" and .key != "EC2_SSH_KEY") | "\(.key)=\(.value)"' >> $GITHUB_ENV
          
          # 확인 메시지 (실제 값은 표시되지 않음)
          echo "환경변수가 성공적으로 설정되었습니다."
          echo "설정된 변수 목록 (값은 보안상 표시되지 않음):"
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries | .[] | select(.key != "GITHUB_TOKEN" and .key != "EC2_SSH_KEY") | .key'

      - name: Build with Gradle
        id: build
        run: |
          # 테스트 환경에 환경변수를 시스템 속성으로 전달
          ./gradlew build -Dorg.gradle.project.systemProp.spring.profiles.active=test
        continue-on-error: true  # 빌드 실패 시에도 워크플로우 계속 진행 (Slack 알림용)

      # 빌드 결과물 저장 (다른 작업에서 사용 가능)
      - name: Upload build artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          retention-days: 1

      # 빌드 실패 시 Slack 알림
      - name: Notify Slack on Build Failure
        if: steps.build.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000", 
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "브랜치 푸시 후 빌드 실패 :x:",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.event.head_commit.message }}",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.event.head_commit.author.name }}",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  # CodeQL 분석 작업 (빌드와 병렬로 실행)
  codeql-analysis:
    runs-on: ubuntu-latest
    outputs:
      codeql_status: ${{ steps.codeql.outcome }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # CodeQL 분석을 위해 전체 히스토리 가져오기

      # 모든 시크릿을 환경변수로 변환하는 단계
      - name: Export secrets as environment variables
        run: |
          # GitHub 시크릿을 JSON으로 변환하고 파싱하여 GitHub 환경 파일에 추가
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries | .[] | select(.key != "GITHUB_TOKEN" and .key != "EC2_SSH_KEY") | "\(.key)=\(.value)"' >> $GITHUB_ENV
          
          # 확인 메시지 (실제 값은 표시되지 않음)
          echo "환경변수가 성공적으로 설정되었습니다."
          echo "설정된 변수 목록 (값은 보안상 표시되지 않음):"
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries | .[] | select(.key != "GITHUB_TOKEN" and .key != "EC2_SSH_KEY") | .key'

      # Java 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # CodeQL 초기화
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java  # 필요에 따라 javascript, python 등 추가 가능
          queries: security-and-quality

      # CodeQL 자동 빌드 실행
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        env:
          # 자동 빌드에 환경변수 전달
          SPRING_PROFILES_ACTIVE: test

      # CodeQL 분석 실행
      - name: Perform CodeQL Analysis
        id: codeql
        uses: github/codeql-action/analyze@v3
        continue-on-error: true  # CodeQL 실패 시에도 워크플로우 계속 진행 (Slack 알림용)

      # CodeQL 분석 실패 시 Slack 알림
      - name: Notify Slack on CodeQL Failure
        if: steps.codeql.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff9900", 
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "브랜치 푸시 후 CodeQL 분석 실패 :warning:",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.event.head_commit.message }}",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.event.head_commit.author.name }}",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  # 보안 취약점 확인 작업 (CodeQL 분석 후 실행)
  security-check:
    needs: [ codeql-analysis ]
    if: needs.codeql-analysis.outputs.codeql_status == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check for CodeQL Security Issues
        id: check_security_issues
        run: |
          # GitHub API를 사용하여 코드 스캐닝 알림 확인
          ALERTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open")
          
          # 열린 알림 수 계산
          ALERT_COUNT=$(echo $ALERTS | jq length)
          
          echo "Security alert count: $ALERT_COUNT"
          echo "alert_count=$ALERT_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$ALERT_COUNT" -gt 0 ]; then
            echo "Security vulnerabilities found!"
          fi

      # 보안 취약점 발견 시 Slack 알림
      - name: Notify Slack on Security Vulnerabilities
        if: steps.check_security_issues.outputs.alert_count > 0
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          # 커밋 메시지를 JSON 호환 형식으로 변환
          COMMIT_MESSAGE: ${{ toJSON(github.event.head_commit.message) }}
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff9900", 
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "브랜치 푸시 후 CodeQL 분석에서 보안 취약점 발견 :warning:",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": ${{ env.COMMIT_MESSAGE }},
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.event.head_commit.author.name }}",
                      "short": true
                    },
                    {
                      "title": "취약점 수",
                      "value": "${{ steps.check_security_issues.outputs.alert_count }}개",
                      "short": true
                    },
                    {
                      "title": "보안 취약점 확인",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/security/code-scanning|Security Dashboard에서 확인>",
                      "short": false
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>",
                      "short": false
                    }
                  ]      
                }
              ]
            }